# -*- coding: utf-8 -*-
"""Stage0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13J9IfnYjM3WHAbZ3MsVlXF6RGmlS6om-

## Stage 0
"""

# Simple Team Info + Favorite Gene Script (Google Colab version)

# Define your team info below
team = [
    {
        "name": "Chioma Nnadi",
        "slack": "@Chioma",
        "country": "Nigeria",
        "hobby": "Writing",
        "affiliations": "None",
        "favorite_gene": "BRCA1",
        "favorite_gene_ID": "670",
        "gene_sequence": "GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGC"
    },
    {
        "name": "Kashish Arora",
        "slack": "@Kashish",
        "country": "India",
        "hobby": "Reading",
        "affiliations": "University of Glasgow",
        "favorite_gene": "CDKN1A (p21) promoter",
        "favorite_gene_ID": "1026",
        "gene_sequence": "GAACATGTCCCAACATGTTG"
    },
    {
        "name": "Keola Merl Joanes",
        "slack": "@Keola",
        "country": "India",
        "hobby": "Reading",
        "affiliations": "PCCAS",
        "favorite_gene": "HBB gene",
        "favorite_gene_ID": "3043",
        "gene_sequence": "GGGGGATATTATGAAGGGCCTTGAGCATCTGGATTCTGCCTAATAAAAAACATTTATTTTCATTGCAA"
    },
    {
        "name": "Lavinia Dorothea F Joseph",
        "slack": "@Lavinia",
        "country": "Antigua & Barbuda",
        "hobby": "Sudoku",
        "affiliations": "University Mohammed V, Faculty of Medicine and Pharmacy",
        "favorite_gene": "DHh gene",
        "favorite_gene_ID": "50846",
        "gene_sequence": "GTTCCAGGTAGTGCCTGAAACTACTTTTCTGAAGAAGTATAATTAAAAGTAATCTTGTTTTGAGAA"
    },
    {
        "name": "Atairoro Joshua",
        "slack": "@Atairoro Joshua",
        "country": "Nigeria",
        "hobby": "Music",
        "affiliations": "None",
        "favorite_gene": "BRCA1",
        "favorite_gene_ID": "672",
        "gene_sequence": "ATGGAAGTTGTCATTTTATAAAGTCAGTAGTTTCTTTGGCAGCAATGCCAGGAAAGGCTCTGAGGAA"
    },
    {
        "name": "Bezaleel Akinbami",
        "slack": "@B3z",
        "country": "Nigeria",
        "hobby": "Gaming",
        "affiliations": "Biomedical Engineering, Johns Hopkins University",
        "favorite_gene": "None",
        "favorite_gene_ID": "None",
        "gene_sequence": "None"
    },
    {
        "name": "Sharon Addy",
        "slack": "@Sharon Addy",
        "country": "Ghana",
        "hobby": "Repairing damaged electronics",
        "affiliations": "None",
        "favorite_gene": "MIR1-1",
        "favorite_gene_ID": "406904",
        "gene_sequence": "UGGAAUGUAAAGAAGUAUGUAU"
    },
    {
        "name": "Jegede Joseph.O",
        "slack": "@Joseph",
        "country": "Nigeria",
        "hobby": "Gaming",
        "affiliations": "Obafemi Awolowo University",
        "favorite_gene": "None",
        "favorite_gene_ID": "None",
        "gene_sequence": "None "
    }
]

# Function to validate DNA sequences (only A, C, G, T allowed)
def is_valid_dna(seq):
    return all(base in "ACGTacgt" for base in seq) and len(seq) > 0

# Print team info nicely
print("=== Team Members and Their Favorite Genes ===\n")
for member in team:
    print(f"Name: {member['name']}")
    print(f"Slack Username: {member['slack']}")
    print(f"Country: {member['country']}")
    print(f"Hobby: {member['hobby']}")
    print(f"Affiliations: {member['affiliations']}")
    print(f"Favorite Gene: {member['favorite_gene']}")
    print(f"Favorite Gene ID: {member['favorite_gene_ID']}")

    seq = member['gene_sequence']
    if is_valid_dna(seq):
        print(f"DNA Sequence: {seq}")
    else:
        print("DNA Sequence: Invalid or not provided")

    print("-" * 60)

# Optional: print sequences in FASTA-style format
print("\n=== FASTA Format ===\n")
for member in team:
    seq = member['gene_sequence']
    header = f">{member['name'].replace(' ', '_')}|{member['favorite_gene']}"
    print(header)
    print(seq)